; ability constants ids
    const_def
    const NO_ABILITY
    const OVERGROW
    const BLAZE
    const TORRENT
    const SHIELD_DUST
    const SHED_SKIN
    const COMPOUND_EYES
    const SWARM
    const KEEN_EYE
    const GUTS
    const INTIMIDATE
    const STATIC
    const SAND_VEIL
    const POISON_POINT
    const CUTE_CHARM
    const FLASH_FIRE
    const INNER_FOCUS
    const CHLOROPHYLL
    const EFFECT_SPORE
    const LIMBER
    const CLOUD_NINE
    const VITAL_SPIRIT
    const WATER_ABSORB
    const CLEAR_BODY
    const STURDY
    const OWN_TEMPO
    const THICK_FAT
    const STICKY_HOLD
    const SHELL_ARMOR
    const LEVITATE
    const INSOMNIA
    const ROCK_HEAD
    const SERENE_GRACE
    const SWIFT_SWIM
    const NATURAL_CURE
    const FLAME_BODY
    const HYPER_CUTTER
    const VOLT_ABSORB
    const IMMUNITY
    const PRESSURE
    const SYNCHRONIZE
    const HUGE_POWER
    const SNOW_WARNING
    const SUCTION_CUPS
    const SNIPER
    const SANDSTREAM
NUM_ABILITIES EQU const_value - 1